name: Research Project Runbook
description: Use this template when starting a new UX research project. This will create a high-level checklist to guide you through building tickets for upcoming sprints.
title:  "Create new research project: {Project/Trial} "
labels: ["research", "design", "product management"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of research project's overall purpose
      placeholder:
      value:
    validations:
      required: true


    id: acceptance-criteria
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
