name: Project Runbook
description: Use this template when starting a new UX research project. This will create a high-level checklist to guide you through building tickets for upcoming sprints.
title:  "Create new research project: {Project} "
labels: ["research", "design", "product management"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of research project's overall purpose
      placeholder:
      value:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: You probably don't need to edit this at all.
      placeholder:
      value: |
        - [ ] Create a research [Epic](https://github.com/jcklpe/research-ops-hackpack/issues/new?assignees=octocat&labels=research%2Cdesign%2Cproduct+management%2Cepic&template=epic.yaml&title=%7BProject%2FTrial%7D+Epic).
        - [ ] Create a research project folder.
        - [ ] Create [project brief issue](https://github.com/jcklpe/research-ops-hackpack/issues/new?assignees=octocat&labels=research%2Cdesign&template=project-brief.yaml&title=Write+new+project+brief%3A+%7BProject%7D+).
        - [ ] All tickets have been created and assigned
    validations:
      required: true