name: Research Project Runbook
description: Use this template when starting a new UX research project. This will create a high-level checklist to guide you through building tickets for upcoming sprints.
title:  "Create new research project: {Project/Trial} "
labels: ["research", "design", "product management"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of research project's overall purpose
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: You probably don't need to edit this at all.
      placeholder:
      value: |
        - [ ] Create a research [Epic](https://github.com/jcklpe/research-ops-hackpack/issues/new?assignees=octocat&labels=research%2Cdesign%2Cproduct+management%2Cepic&template=epic.yaml&title=%7BProject%2FTrial%7D+Epic) for your product/initiative
        - [ ] Create a research project folder and write project brief.
        - [ ] Create a [research brief and plan issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Design%2C+Research&template=research-plan-and-conversation-guide.md&title=Draft+%5BPRODUCT%2FINITIATIVE%5D+Research+Plan+%26+Conversation+Guide)
        - [ ] Create a [recruitment and scheduling issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Design%2C+Research&template=research-recruitment-and-scheduling.md&title=Recruit+and+schedule+participants+for+%5BPRODUCT%2FINITIATIVE%5D+research)
        - [ ] Create a [Research Sessions issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Design%2C+Research&template=research-sessions.md&title=Conduct+%5BPRODUCT%2FINITIATIVE%5D+Research+Sessions)
        - [ ] Create a [Research Synthesis and Review issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Design%2C+Research&template=research-synthesis-and-topline-report.md&title=Synthesize+%5BPRODUCT%2FINITIATIVE%5D+Research+%26+Create+Topline+Report)
        - [ ] Create a [Research Readout & Documentation issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Design%2C+Research&template=research-readout-and-documentation.md&title=Conduct+%5BPRODUCT%2FINITIATIVE%5D+Research+Readout+and+Document+Report+in+Research+Repository)
        - [ ] Add all the above issues to the Research Epic and add dependencies


        - [ ] All tickets have been created and assigned
    validations:
      required: true