name: Research Project Runbook
description: Use this template when starting a new UX research project. This will create a high-level checklist to guide you through building tickets for upcoming sprints.
title:  "Create new research project: {Project/Trial} "
labels: ["research", "design", "product management"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of research project's overall purpose
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false