name: Research Project Runbook
description: Use this template when starting a new UX research project. This will create a high-level checklist to guide you through building tickets for upcoming sprints.
title:  "Create new research project: {Project/Trial} "
labels: ["research", "design", "product management"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of research project's overall purpose
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Checklist of tasks or deliverables needed in order to commplete the issue.
      placeholder:
      value:
    validations:
      required: true
