name: Research Sessions
description: Use this template when you are conducting research sessions
title:  "Conduct {Project/Trial} research sessions "
labels: ["research", "design",]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Leave this open for notes
      placeholder:
      value:
    validations:
      required: false
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: You probably don't need to edit this at all.
      placeholder:
      value: |
        - [ ] Conduct all sessions
        - [ ] Store all field notes and artifacts in the sessions artifact folder
        - [ ] Update recruitment tracker
    validations:
      required: true