name: Trial Runbook
description: High level checklist for starting a new trial.
title:  "Create new research trial: {Project/Trial} "
labels: ["research", "design", "product management"]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of research trials goals
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      description: You probably don't need to edit this at all.
      placeholder:
      value: |
        - [ ] Create a [trial brief and plan issue]()
        - [ ] Create a [recruitment and scheduling issue](https://github.com/jcklpe/research-ops-hackpack/issues/new?assignees=octocat&labels=research%2Cdesign&template=recruitment-and-scheduling.yaml&title=Recruit%2Fschedule+participants+for+%7BProject%2FTrial%7D+research)
        - [ ] Create a [Research Sessions issue]()
        - [ ] Create a [Research Synthesis and Review issue]()
        - [ ] Create a [Research Readout & Documentation issue]()
        - [ ] Add all the above issues to the research project Epic
    validations:
      required: true
